version: '3'
services:
  mysql_API:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD= #pass del root es root
      - MYSQL_DATABASE=
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password #pass del user
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
